### ISSUE TITLE
Update kord version to implement mute/timeout features

### ISSUE THREAD

**Issue by misterquestions** [Kotlin-Discord/kord-extensions#121]
# Summary

The kord dependency must be updated to support the timeout feature that was recently implemented in discord. This depends on [the following pr](https://github.com/kordlib/kord/pull/448) to be merged.

# Current Behaviour

No support for `communicationDisabledUntil` inside guild member

# Preferred Behaviour

Have this property aswell when using this framework

**Comment by gdude2002** [comment]
Hello, thanks for the ticket! 

The pull request you've linked hasn't been merged yet. As soon as it has been, and Kord's GitHub Actions have been run, the changes will be available on Kord's snapshot branch - so it'll be immediately available for KordEx 1.5.1-SNAPSHOT with no changes required by us.

I highly doubt this PR is going to somehow result in a new stable version of Kord, so you'll need to use snapshots at that point regardless.
