### ISSUE TITLE
Arguments should be ordered properly

### ISSUE THREAD

**Issue by DRSchlaubi** [Kotlin-Discord/kord-extensions#123]
I have a problem that when I have an argument system like this

```kotlin
class SuperArguments : Arguments()
  val x = oprionalInt(...)
}

class MyArgs : SuperArguments() {
  val y = int(...)
```

Then `x` will be over `y` in `Arguments.args` which Discord doesn't like

One possible way of solving this would be to just put all required args before all optional args, that way we sorta retain the order but still register them like discord wants us to

Another way would be to add an index to the argument builders

**Comment by gdude2002** [comment]
Because of how class instantiation order works, I don't think doing anything that relies on the order of instantiating the classes makes sense. However, reordering the declarations is also not going to happen - arguments are always parsed in precisely the order they're defined, which is something that's absolutely required for some use-cases.

The problem here is that there's really no good solution - we can't provide a different way of adding the arguments from the subtype because there'd be no access to its properties, and we can't change the order of the arguments as provided by the user. I don't think there's a realistic way to do this in Kotlin.

**Comment by DRSchlaubi** [comment]
> However, reordering the declarations is also not going to happen - arguments are always parsed in precisely the order they're defined, which is something that's absolutely required for some use-cases.

That makes no sense whatsoever, re-ordering like this would not affect anything, if the arguments are already ordered correctly, nothing would happen, if it's not the order is broken anyway, so there is no reason to preserve it, as you can't do anything with it.

But if you want to insist, that this order is hyper important, you can simply store arguments as an [IndexedValue](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-indexed-value/) and then order by that, it would cause some problems with not duplicating indices, but I think those can be fixed

**Comment by gdude2002** [comment]
> That makes no sense whatsoever, re-ordering like this would not affect anything, if the arguments are already ordered correctly, nothing would happen, if it's not the order is broken anyway, so there is no reason to preserve it, as you can't do anything with it.

```kotlin
val one by string { ... }
val two by somethingElse { 
    ....

    validate {
        failIf(one == ...)
    }
}
```

A logical API is important, nobody is omnipotent - esp. not you or I.

> But if you want to insist, that this order is hyper important, you can simply store arguments as an [IndexedValue](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-indexed-value/) and then order by that, it would cause some problems with not duplicating indices, but I think those can be fixed

Wouldn't that have the same problem?

**Comment by DRSchlaubi** [comment]
> > That makes no sense whatsoever, re-ordering like this would not affect anything, if the arguments are already ordered correctly, nothing would happen, if it's not the order is broken anyway, so there is no reason to preserve it, as you can't do anything with it.
> 
> ```kotlin
> val one by string { ... }
> val two by somethingElse { 
>     ....
> 
>     validate {
>         failIf(one == ...)
>     }
> }
> ```
> 
> A logical API is important, nobody is omnipotent - esp. not you or I.

And how does ordering break this API? If the order matches Discord requirements, it is the same order.

If it's not, we use the partition function to determine optional and non-optional arguments and simply move the required ones before the optional ones, so it only happens if it is really needed

Or simply add val autoSort: Boolean = false to the Arguments class and then only do exactly that if some class sets it to true, then nothing would break, except if you explicitly tell it to break

**Comment by gdude2002** [comment]
> so it only happens if it is really needed

This is an unexpected behaviour for an otherwise straightforward and predictable API. Hidden gotchas like that are definitely not wise to include, IMO.

**Comment by DRSchlaubi** [comment]
> > so it only happens if it is really needed
> 
> This is an unexpected behaviour for an otherwise straightforward and predictable API. Hidden gotchas like that are definitely not wise to include, IMO.

I don't see anything unpredictable making it opt-in only

**Comment by gdude2002** [comment]
Even then it's still kinda unpredictable, you're just allowed to turn the unpredictable feature on or off

**Comment by DRSchlaubi** [comment]
> Even then it's still kinda unpredictable, you're just allowed to turn the unpredictable feature on or off

That imo would be a worthy trade-off to work around this Discord restriction, if the functionality is properly documented

**Comment by DRSchlaubi** [comment]
Since https://github.com/Kord-Extensions/kord-extensions/commit/6d2401a585145308bb43f746dde4052efa2e024d you can actually create your own arguments class modifying sorting behavior

https://github.com/DRSchlaubi/mikbot/blob/9a6d0d668f335996bab7712ffa97d427cbac5452/api/src/main/kotlin/dev/schlaubi/mikbot/plugin/api/util/SortedArguments.kt#L61-L74

<blockquote><img src="https://opengraph.githubassets.com/ee883fbb7f4c4473b559d819f02c7486bbbefb438b9007a361e0d023b1d77bf3/DRSchlaubi/mikbot" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/DRSchlaubi/mikbot/blob/9a6d0d668f335996bab7712ffa97d427cbac5452/api/src/main/kotlin/dev/schlaubi/mikbot/plugin/api/util/SortedArguments.kt">mikbot/api/src/main/kotlin/dev/schlaubi/mikbot/plugin/api/util/SortedArguments.kt at 9a6d0d668f335996bab7712ffa97d427cbac5452 · DRSchlaubi/mikbot</a></strong></div><div>A modular framework for building Discord bots in Kotlin using Kordex and Kord - DRSchlaubi/mikbot</div></blockquote>
