### ISSUE TITLE
Add timeout utility extensions methods

### ISSUE THREAD

**Issue by Ayfri** [Kotlin-Discord/kord-extensions#130]
# Summary

Add a method to easily timeout a member for a duration and a method to disable timeout of a member.

# Current Behaviour

Editing the member `timeoutUntil` or `communicationDisabledUntil` property, if we want to deactivate until now + a duration, we have to include a calculation into our code.

# Preferred Behaviour

Use methods for this.

# Suggestions

```kotlin
/**
 * Disable communication for a member until now + duration.
 * Returns false if the bot cannot set the timeout for the member, otherwise true.
**/
suspend fun MemberBehavior.timeout(duration: Duration): Boolean
// and maybe also
suspend fun MemberBehavior.timeout(seconds: int): Boolean

/**
 * Remove disabled communication for a member.
 * Returns false if the bot cannot enable communication for member, otherwise true.
**/
suspend fun MemberBehavior.stopTimeout()
```

**Comment by gdude2002** [comment]
Done!
