### ISSUE TITLE
The Linkie Mappings System now requires JitPack

### ISSUE THREAD

**Issue by NoComment1105** [Kotlin-Discord/kord-extensions#133]
# Description

* I was adding the mappings extension to my bot
* The bot doesn't start.

# Versions

* KordEx Version 1.5.2-SNAPSHOT (current commit at the time of writing)
* IntelliJ IDEA Ultimate IU-213.6777.52
* 7.3.3
* OpenJDK 17 64-Bit
* Normal, 1.6.10

# Reproduction

* Add mapping extension
* Press the go button
* Error

# Suggestions

* Just need to add JitPack to build script, or what ever is required, to allow hte mappings extension to gather all the required dependencies

**Comment by gdude2002** [comment]
I've updated the README in the latest push. That's all there is to do on our end.
