### ISSUE TITLE
EphemeralInteractionContext broken respondPublic extension function

### ISSUE THREAD

**Issue by Syer10** [Kotlin-Discord/kord-extensions#134]
# Description

Inside com.kotlindiscord.kord.extensions.types.EphemeralInteractionContext.kt there is a extension function that extends PublicInteractionContext instead of EphemeralInteractionContext

# Versions

Kord-Extensions version 1.5.2-RC

# Media

<details>

![uF7AOrf 1](https://user-images.githubusercontent.com/6090655/152821920-b5eb40e2-7306-4fc7-9ae7-9f19c51d6eed.png)
</details>

**Comment by gdude2002** [comment]
Thanks, got it!
