### ISSUE TITLE
Make enum choice converters act the same as regular enum converters in the context of chat commands

### ISSUE THREAD

**Issue by russellbanks** [Kotlin-Discord/kord-extensions#137]
# Summary

When using an enum choice converter on a chat command, it will result in an `java.lang.IllegalStateException: Choice converters may only be used with slash commands` error. In the use case of hybrid commands, it would beneficial to ensure that a hybrid command, utilising an enum choice, can work with a slash command whilst not failing as a chat command.

# Current Behaviour

Using an enum choice on a chat command results in a `java.lang.IllegalStateException: Choice converters may only be used with slash commands` error.

# Preferred Behaviour

An enum choice converter for a chat command should work the same as a normal enum choice converter.

# Suggestions

[#1](https://github.com/qbosst/kordex-hybrid-commands/issues/1) of [Kordex hybrid commands](https://github.com/qbosst/kordex-hybrid-commands) documents this better.

# Media

Using a command with a choice converter:
![image](https://user-images.githubusercontent.com/74878137/155580866-464f59a0-2396-4792-bed6-4ae8b25e8f00.png)

Using the equivalent chat command:
![image](https://user-images.githubusercontent.com/74878137/155581129-ab52a008-f752-4013-b56e-fad790a0809e.png)

**Comment by gdude2002** [comment]
I think we could probably fix up converters a bit like this - I agree that supporting both in the same converter is likely to be the best option.

I'm not sure whether I'll get a chance to work on this soon, however, so I'd suggest making use of the latest snapshot (`1.5.2-SNAPSHOT`) and using a regular enum converter with an autoComplete set up as a workaround temporarily.

**Comment by gdude2002** [comment]
This has just been pushed to `1.8.1-SNAPSHOT`, and should be available in about 15 minutes. Thanks for your patience!

Chat commands should now support choice converters. Users may specify either the keys or values (case-insensitively wherever strings are involved) and an error showing the possible values will be returned if nothing matches.

The [new documentation site](https://docs.kordex.dev) has been updated to match this change.
