### ISSUE TITLE
Add minValue and maxValue to int/decimal argument converters

### ISSUE THREAD

**Issue by Galarzaa90** [Kotlin-Discord/kord-extensions#156]
# Summary

Add `minValue` and `maxValue` options to t`IntConverterBuilder` and `DecimalConverterBuilder` and derivatives.

They are defined here in the documentation: https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure

And they were added to Kord since: https://github.com/kordlib/kord/commit/4a73bfa2146df3980a4cf6c0d5fd613f31b29bbb

# Current Behaviour

It is not possible to use these options, so these validations must be done after receiving the interaction with the `validate` option. While this allows more customization in error messages, it means receiving a command interaction that will be "rejected" by the bot.

# Preferred Behaviour

Being able to use this option would mean that these options will be validated on the client's side, meaning you wouldn't receive the command interaction message if the numbers are invalid.

**Comment by gdude2002** [comment]
This has been added, but could do with some gentle poking - please verify.

**Comment by Galarzaa90** [comment]
Everything seems to be working fine 👍🏼

**Comment by gdude2002** [comment]
Thanks for the confirmation o7
