### ISSUE TITLE
Suggestion: Event cache

### ISSUE THREAD

**Issue by GreemDev** [Kotlin-Discord/kord-extensions#167]
# Summary

The idea here is to provide a data object to an arbitrary event KordEx receives when dispatched.

# Current Behaviour

None, potential workaround could entail some sort of weird map cache that holds the objects via an ID? but that ID wouldn't be very intuitive. Haven't ever tried it, just thought it might be possible when writing this.

# Preferred Behaviour

New class, `EventCache`, for example.
EventCache is an object added to the relevant Context objects as `val cache: EventCache`

```kt
override suspend fun setup() {
  event<MessageReceivedEvent> {
    check {
      cache["guildSettings"] = someGettingMethod(event.guild?.id ?: 0)
      if (cache["guildSettings"] == null)
          fail("404")
      else pass()
    }
    action {
      //we can safely assume that guild settings are not null.
      if (event.message.content.startsWith(cache.get<GuildSettings>("guildSettings").commandPrefix)) {
        //now the prefix has been checked and we only called the DB once
        //yes i know you'd probably put this logic in the check but this isn't the point, this example is to show
      }
    }
  }
}
```

**Comment by gdude2002** [comment]
Pushed in https://github.com/Kord-Extensions/kord-extensions/commit/a8eeca528172d4ccf9954ca1c918480d82694de6

* Checks and action blocks for commands, components and events will have a `cache` MutableMap with string keys and non-nullable values
* All maps with non-nullable values now have extra `.getOf`, `.getOfOrNull` and `.getOfOrDefault` convenience functions for casting

See what you think!

**Comment by GreemDev** [comment]
Looks good to me. Thanks!
