### ISSUE TITLE
`PKMessageCreateEvent` occasionally fires twice due to low delay with slower PK times

### ISSUE THREAD

**Issue by SilverAndro** [Kotlin-Discord/kord-extensions#170]
# Description
The PKMessageCreateEvent occasionally fires twice due to low delay and/or slower PK times

# Reproduction
Inconsistent due to factors outside of a testing environment's control

# Suggestions

Additionally, switching the logic to watching for a new, proxied message rather than the deletion of the old one may improve detection, as PK will not delete the message until it knows that a proxied one has been sent successfully.

**Comment by gdude2002** [comment]
> switching the logic to watching for a new, proxied message rather than the deletion of the old one...

How do you propose this should work? I don't really see it changing too much, given that you can't take back an event, and we'd still need to wait for that message to appear.

**Comment by SilverAndro** [comment]
I don't believe it would completely solve it, but watching for a new one instead would reduce the amount of time until a proxy is "finished" which would hopefully bring down the average time to wait, since youre cutting out waiting for another interaction from PK after the proxied version is sent.

Basically I'm not aware of anything particularly special about the deletion other than being a last step, all the information should be available once the webhook message is available, to my understanding 

(Although it does occur to me that may cause issues with reproxy? I don't think it would be too significant though)

**Comment by gdude2002** [comment]
For the time being, I'm just going to add one second to the delays, since I can't really motivate myself to rewrite this thing at the moment

**Comment by SilverAndro** [comment]
Fair enough

**Comment by gdude2002** [comment]
That should be in the latest push, which will be available in around 15 minutes.

**Comment by SilverAndro** [comment]
Yep seems to work, thanks much
