### ISSUE TITLE
UnProxiedMessageDeleteEvent throws ClientRequestException on message delete

### ISSUE THREAD

**Issue by NoComment1105** [Kotlin-Discord/kord-extensions#173]
# Description

When an unproxied message is deleted, the PluralKit module appears to search the PluralKit API for said message, and throws a `ClientRequestException` when it's not found.

# Reproduction

Make use of the `UnProxiedMessageDeleteEvent`

# Code Examples

```kotlin
    override suspend fun setup() {
        event<UnProxiedMessageDeleteEvent> {
            action {
                kordLogger.info { "h" }
            }
        }
    }
```

# Media

![image](https://user-images.githubusercontent.com/67918617/184480618-52b52287-d7ef-4c2b-a1c8-1309cfca1129.png)

**Comment by gdude2002** [comment]
Not a bug per se, I checked the code and everything is being handled correctly. What's happening here is that the `getMessage` function is logging the exception, but this function isn't used directly by the extension - it's called by `getMessageOrNull`, which is not currently capable of swallowing the log message.

I think this is probably just how it's going to have to be for the time being, as fixing it appropriately would require a surprising amount of work.
