### ISSUE TITLE
ExtensibleBot#setup trying to use non-existent method

### ISSUE THREAD

**Issue by GrowlyX** [Kotlin-Discord/kord-extensions#178]
# Description
When using kord-extensions with the latest kord-core `0.8.0-M16` version, an error is thrown when then `ExtensibleBot#start` or `ExtensibleBot#startAsync` function is called. (Internally, these functions call the `setup` function which is where this exception is being thrown)

The stack trace for this exception can be viewed here:
https://pastes.dev/8Se2Xmlv3L

# Versions

My `build.gradle.kts` script can be viewed here:
https://pastes.dev/2gZMkcEz3p

Gradle version: `7.4.2`
JDK & JRE version: `17`

Kotlin version: `1.7.10`
Kotlin coroutines version: `1.6.4`

**Comment by gdude2002** [comment]
You're very out of date - remove your dependency on Kord, and switch to KordEx `1.5.5-SNAPSHOT`.

I'm working on Forms at the moment, which will take a while, but I may be able to put out a release targeting `M16` later. For now, KordEx depends on Kord `0.8.x-SNAPSHOT`.

**Comment by GrowlyX** [comment]
> You're very out of date - remove your dependency on Kord, and switch to KordEx `1.5.5-SNAPSHOT`.
> 
> I'm working on Forms at the moment, which will take a while, but I may be able to put out a release targeting `M16` later. For now, KordEx depends on Kord `0.8.x-SNAPSHOT`.

Cool thanks, figured there was some new version. Initially, I just used the release version 1.5.2 listed in the README but I'll try 1.5.5 out.
