### ISSUE TITLE
Add method to ExtensibleBot to allow us to configure kord's cache

### ISSUE THREAD

**Issue by bosukas** [Kotlin-Discord/kord-extensions#19]
# Summary

Could we have a method for configurating Kord's cache? 
This is useful for when people want to turn off the caching of certain objects or when they want to register their own objects to cache.

# Current Behaviour

At the moment, we can only choose how many messages to cache, using messageCacheSize
We could use DataCache#register however this is limited, as it doesn't let us configure the maximum amount of cached entities allowed. 

# Preferred Behaviour

I would like a method that allows us to configure the cache in the ExtensibleBot class. This method could be a builder method, like how the start method is and should give us access to KordCacheBuilder.
Another Idea could be to add a method for configuring cache in the StartBuilder instead of ExtensibleBot

**Comment by gdude2002** [comment]
I think this issue would be better served with a builder for creating and configuring the ExtensibleBot class. I've been meaning to do this for a while, so I think I'll roll this issue's change into that changeset.

**Comment by bosukas** [comment]
> I think this issue would be better served with a builder for creating and configuring the ExtensibleBot class. I've been meaning to do this for a while, so I think I'll roll this issue's change into that changeset.

Either way works, I would just like to see something for configuring cache, thank you

**Comment by gdude2002** [comment]
Fixed in https://github.com/Kord-Extensions/kord-extensions/commit/4e5aba04bff8e3c410881f647f6bab29148ec50f
