### ISSUE TITLE
Kord forums branch release (1.5.6-forums-SNAPSHOT)

### ISSUE THREAD

**Issue by thebrightspark** [Kotlin-Discord/kord-extensions#206]
# Description

After the whole issue with Nexus and releases being lost, we also lost the alternative release with Kord's current forums support. The KordEx release was previously `1.5.6-forums-SNAPSHOT`. It'd be great to have this also re-uploaded given it's also a latest KordEx release.

[My original question about this on Discord](https://discord.com/channels/705370076248932402/787281457453727744/1075587067565834322)

**Comment by gdude2002** [comment]
I've merged the latest changes from `develop` into that branch, so a release should be building now.
