### ISSUE TITLE
Support ProxyFox API

### ISSUE THREAD

**Issue by Oliver-makes-code** [Kotlin-Discord/kord-extensions#221]
# Summary

We're getting closer to the release of ProxyFox's API, 
and I'd like for things to have support for it.
I'm creating this as a tracking issue for support for it.
For privacy reasons, we have elected to make only the `/messages` endpoint not require a token.
The model for a message (currently at least) is almost the same as PK's model,
with the exceptions of `id` being renamed to `proxied`,
and the `system` and `member` fields being IDs rather than full objects.
[Link to source file for message model](<https://github.com/The-ProxyFox-Group/ProxyFox/blob/dev/2.1/modules/api/src/main/kotlin/dev/proxyfox/api/models/Message.kt>)

# Preferred Behaviour

Similar API to the PluralKit extension,
maybe split common code so `ProxiedMessage*Event` and `UnProxiedMessage*Event` work for both PK and PF 

# Extra

API endpoints and models aren't yet finalized.
If you have any suggestions for any changes we should make,
feel free to mention them here.

CC: @Ampflower, @TibiNonEst, as they work on ProxyFox

**Comment by gdude2002** [comment]
Interesting - I have nothing against proper support for other plural-proxying solutions. However, I need to point out that the model you linked to is close to useless because you manually serialize everything to a string - the point of kotlinx.serialization is that you can use rich, self-documenting types, so without proper tying or documentation, this isn't going to be enough information to figure things out.

**Comment by Oliver-makes-code** [comment]
Oh, I didn't notice that, I think it was done this way because we were still in the middle of migrating to kx.ser from gson.
I'll look into fixing it

**Comment by gdude2002** [comment]
Has there been any movement on the development of this API?

If so, have you made sure it'll scale properly under load? Make sure you stress test before any work is done here.

**Comment by gdude2002** [comment]
Apparently, ProxyFox is shutting down. For that reason, I guess supporting the API doesn't really make sense anymore, so I'll close this.
