### ISSUE TITLE
Use generics for ExtensibleBotBuilder

### ISSUE THREAD

**Issue by bosukas** [Kotlin-Discord/kord-extensions#23]
# Summary

The bot attribute in extension classes can be overridden to support custom classes that extend ExtensibleBot.
```kt
class CustomExtension(override val bot: CustomBot): Extension(bot)
```

However, when we do this we now need to use an instance of a CustomBot to create the extension, there is currently no clean way of adding this new extension with the extensions builder without casting or extending ExtensibleBotBuilder and creating your own method for it.

# Current Behaviour

We can only use ExtensibleBot to add extensions 

# Preferred Behaviour

I would like to be able to add extensions that require `CustomBot` without casting or creating my own method for it

# Suggestions

I feel as though this is best solved using generics.
We could have something like:
```kt
open class ExtensibleBotBuilder<T: ExtensibleBot> {
    
    open val extensionsBuilder: ExtensionsBuilder<T> = ExtensionsBuilder<T>()
    
    open fun extensions(builder: ExtensionsBuilder<T>.() -> Unit) {
        builder(extensionsBuilder)
    }
    
    open class ExtensionsBuilder<T: ExtensibleBot> {
        open val extensions: MutableList<(T) -> Extension> = mutableListOf()
        
        open fun add(builder: (T) -> Extension) {
            extensions.add(builder)
        }
    }
}
```

**Comment by gdude2002** [comment]
Apologies for taking so long to get to this.

Can you explain what the problem is in more specific terms, and how this solves it? 

My understanding of the issue is that `ExtensibleBotBuilder` assumes an instance of `ExtensibleBot`, which means that it will accept subclasses as well, [but `ExtensibleBot`'s own methods for registering extensions mean that a value of type `ExtensibleBot` will be passed into the extension constructor](https://github.com/Kord-Extensions/kord-extensions/blob/root/kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/ExtensibleBot.kt#L305). I don't see how making the builder generic will solve this problem in the slightest - can you elaborate?

**Comment by bosukas** [comment]
Yeah, when you override the bot attribute in the Extension class, you then need an instance of `CustomBot` to create that Extension
```kt
class CustomExtension(bot: CustomBot): Extension(bot)

val bot = CustomBot(token)

val ext = CustomExtension(bot)
```
```kt
val bot = ExtensibleBot(token)

val ext = CustomExtension(bot) // wont work
```

However, in the `ExtensibleBotBuilder` you can only add extensions with `ExtensibleBot`, so you would have to add the extension like this:
```kt
extensions {
    add { bot: ExtensibleBot -> CustomExtension(bot as CustomBot) }
}
```
I just feel as though that's a bit messy and can cause problems later.

After looking at the kord-extensions code a bit more, I don't think solving this will be as easy as what I suggested above.
I'm not really sure how we could go about solving this so maybe I should close this issue, i'm not sure.

**Comment by gdude2002** [comment]
Not sure why you'd close an issue that needs more thought, that seems counter-productive. I think I see the problem, though - it's worth a try at least.

**Comment by gdude2002** [comment]
I did end up giving this a try a few days ago, and ran into quite a few problems. Instead of trying to solve things this way, I'm going to prioritize making it easier to do what you need without subclassing `ExtensibleBot`.
