### ISSUE TITLE
StringConverter length validation translation keys switched

### ISSUE THREAD

**Issue by Iliasgx** [Kotlin-Discord/kord-extensions#290]
# Description

The translation keys used to throw a `DiscordRelayedException` in the `StringConverter` are switched in case a length requirement is not met.

- `minLength` req not met uses the key: `converters.string.error.invalid.tooLong`
- `maxLength` req not met uses the key: `converters.string.error.invalid.tooShort`

# Source code

https://github.com/Kord-Extensions/kord-extensions/blob/377d0f1e3816ce7de903aafcfc2415c42b761e1c/kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/commands/converters/impl/StringConverter.kt#L55-L71

# Suggestions
Simple solution, the translation keys should be switched:
- `minLength` req not met: `converters.string.error.invalid.tooShort`
- `maxLength` req not met: `converters.string.error.invalid.tooLong`

**Comment by gdude2002** [comment]
Good catch, thank you!
