### ISSUE TITLE
Revert Commit 487370b

### ISSUE THREAD

**Issue by mrcbax** [Kotlin-Discord/kord-extensions#294]
https://github.com/Kord-Extensions/kord-extensions/commit/487370bc658c74877072f6d927e7dd545cad92a1

There are several downstream bots that blindly have your extPhishing enabled, including some very large bots like lilybot.

I understand your intention was to prevent the domain which shall not be named from gaining popularity.

Unfortunately your antics have had the opposite effect. People are tricking others into sending the domain so that they get kicked from servers.

**Comment by NoComment1105** [comment]
Lilybot developer here. Lily does not have the phishing extension "blindly enabled". I read every commit before updating and I believe this change was beneficial and continued with the update. I'd prefer to hear further information on this matter before this gets reversed. If your users are tricking other users, you should be concerned with the "tricksters" more than a safety system.

**Comment by gdude2002** [comment]
The domain has been permanently suspended as of today, so I don't mind removing it from the list.

That said, this is 100% a moderation problem. Server staff should be timing out, kicking or banning members that use moderation tooling to trick users into getting kicked.

**Comment by crosby-moe** [comment]
I would understand immediate kicking, or at least some form of punishment, for an actual phishing site, something where clicking on the link would actually cause some harm.

This is just.. a data broker site. There are hundreds of data broker sites, some of them arguably less trustworthy than spy.pet, why is this one specifically being singled out?

This just seems really reactionary and opinionated for no reason, like spy.pet is an actual thing happening on discord, and discussion surrounding it should be encouraged, not a cause for immediate expulsion without warning.

**Comment by TheOnlyWayUp** [comment]
Agree, kicking is unwarranted (and extreme).

The domain itself poses no threat to users who visit it.

**Comment by gdude2002** [comment]
Given the history behind the spy.pet developer and the way it functions, it's pretty difficult to say whether the site itself was directly dangerous, even though it was specifically targeting multiple trans and cis women and revealing some of their private information.

That aside, automated advertising had been seen in a couple of places, and realistically any revenue going to something this detestable is a bad thing.

I'll be locking this issue now, as I find the number of unrecognised accounts piling into here suspicious.
