### ISSUE TITLE
Converter Validation

### ISSUE THREAD

**Issue by bosukas** [Kotlin-Discord/kord-extensions#30]
# Summary

Currently we don't have a way validating data without sub-classing the converters.
For example, we may want a string that can only have a maximum x amount of characters or an integer that cant be lower than y.

# Current Behaviour

The way to do this right now is to check for this inside the action method. 

```kt
command(::Args) {
    name = "test"
    
    action {
        if (arguments.message > 300) {
            // output error
        }
        else if(arguments.message < 10) {
            // output error
        } 
    }
}
```

Or subclass the converter method (not going to show an example)

# Preferred Behaviour

We could have something like this, where the string argument gives us a lambda argument, where inside we can validate the argument.
In the case of data not being valid, we could throw the parse exception. 

```kt
class Args: Arguments() {
    val message by string("message", "the message") {
        if (it.length > 300) {
            throw ParseException("Message cannot be longer than 300 characters.")
        } 
        else if(it.length < 10) {
            throw ParseException("Message cannot be shorter than 10 characters.")
        }
    }
}
```

We could also have default validators for common checks 
```kt
fun Arguments.lengthCheck(min: Int, max: Int): (String) -> Unit = {
    if(it.length > 300) {
        throw ParseException("String cannot be longer than ${max} characters")
    } 
    else if(it.length < 10) {
        throw ParseException("Message cannot be shorter than ${min} characters")
    }
}
```

**Comment by gdude2002** [comment]
This is now present in the latest snapshot, and, yeah, it basically works how you think it does. Throw a `CommandException` to fail and the exception message will be sent to the user.

**Comment by bosukas** [comment]
Thanks for the change, this seems good. 
Another small thing that I thought of is maybe including the display name of the argument in the lambda?

In this example, `displayName` is the display name of the argument and `input` is the actual input from the user to validate.
```kt
private class TestArgs: Arguments() {
    val message by coalescedString("message", "Your message") { displayName, input ->
        if(input.length > 200) {
            throw CommandException("`$displayName` cannot be longer than 200 characters!")
        } else if(input.length < 5) {
            throw CommandException("`$displayName` cannot be shorter than 5 characters!")
        }
    }
}
```

I feel like this change would help keep error messages more consistent

**Comment by gdude2002** [comment]
That's not really possible under this model, as converters aren't aware of their Arguments parent object. The only thing I can think of that wouldn't require rewriting a good chunk of the logic would be to allow you to stick some kind of token in the string - although then again, you're writing the validator, so you know what the argument is named already.

Is there a use-case for this where you wouldn't be supplying the name to the validator yourself?

**Comment by bosukas** [comment]
I was planning to do something like this

```kt
fun Arguments.lengthCheck(min: Int, max: Int): suspend (String, String) -> Unit = { displayName, input -> 
    if(input.length < min) {
        throw CommandException("$displayName cannot be shorter than $min characters")
    }
    else if(input.length > max) {
        throw CommandException("$displayName cannot be longer than $max characters")
    }
}

class Args: Arguments() {
    val message by string("message", "Your message", lengthCheck(10, 200))
}
```

This is so that I dont have to keep rewriting the same checks over and over again, and also get prevent typos since it re-uses the display name. However, this isn't a need, just something that would be nice so I don't mind if it can't be implemented

**Comment by gdude2002** [comment]
Via some passing of data, I've managed to make validator functions receive the `Argument<*>` object with the converter's metadata.

This is not typed in a way that will allow you to easily get the converter object itself, but it does provide the `displayName` and `description` properties.

**Comment by bosukas** [comment]
This is also perfect, thank you for the changes! :D

**Comment by gdude2002** [comment]
Alrighty, good stuff - I'll close this for now and consider it solved, feel free to reply or poke on Discord if you need any other changes to this.
