### ISSUE TITLE
Bot permissions for commands

### ISSUE THREAD

**Issue by bosukas** [Kotlin-Discord/kord-extensions#31]
# Summary

Add checks for checking if the bot has permission for a command

# Current Behaviour

We can do this with the check function, however if the check fails (the bot doesn't have permission for a command), it will not show up on the help menu.

# Preferred Behaviour

A specific check for bot permissions. The command should still show up on the help menu if the bot does not have permission to it, and when run it should display an error message saying that the bot is missing x and y permissions for this command.]

# Suggestions

Maybe a scope for each command would be fine, like 
```kt
command {
    name = "ban"
    
    botPermissions {
        +Permission.BanMembers
    }
    
    action {
        // ban user
    }
    
}
```

**Comment by gdude2002** [comment]
Here's what I've got for you. It'll be in the next snapshot - please give it a go and let me know what you think!

```kotlin
command {
    name = "requires-perms"
    description = "A command that requires some permissions"

    requirePermissions(Permission.Administrator)

    action {
        message.respond("Looks like I'm an admin. Nice!")
    }
}
```

![image](https://user-images.githubusercontent.com/204153/114300016-1ad7ae80-9ab6-11eb-9c32-42b3f1e193f6.png)

Required perms also show in the help output, by the way.

**Comment by bosukas** [comment]
This is perfect thank you

**Comment by gdude2002** [comment]
Alrighty, good stuff - I'll close this for now and consider it solved, feel free to reply or poke on Discord if you need any other changes to this.
