### ISSUE TITLE
Slash Commands Test Guild

### ISSUE THREAD

**Issue by bosukas** [Kotlin-Discord/kord-extensions#42]
# Summary

When creating slash commands, you have to wait 1 hour for them to update globally, which is a problem when your testing them. To combat this, you create guild specific slash commands and test them out on your own guild since they update instantly. However, when working with a lot of slash commands, it becomes easily forgettable to keep adding your own guild to each slash command, and then removing them when you finish.

# Preferred Behaviour

I think to solve this, we could add an option in the `SlashCommandsBuilder` / `ExtensibleBotBuilder` class to add a testing guild to each slash command. 

This would look something like this.
```kt
slashCommands {
    enabled = true
    
    testGuild = 182931928371293
}
```

When there is no guild defined in the slash command, the `testGuild` from the `SlashCommandsBuilder` will be used.

If for whatever reason, you want to use different guilds while testing, you should be able to override this default guild by just using the guild function in the slash command dsl.

```kt
slashCommand {
    name = "test"
    description = "test"
    guild(3894729342390847234)
    
    action {
        // do stuff
    }
}
```

**Comment by gdude2002** [comment]
The latest push includes a `defaultGuild` property (with DSL functions) in the `slashCommands` DSL.
