### ISSUE TITLE
Paginator : Interaction forgotten

### ISSUE THREAD

**Issue by Distractic** [Kotlin-Discord/kord-extensions#45]
# Description

With the Paginator, when two actions (interaction with a reaction) are made too quickly, the last interaction will be forgotten (so the action linked to the reaction is not applied)

# Version

`kord-extensions:1.4.0-SNAPSHOT`

# Reproduction

Just create a Paginator (custom or use the one generated by help command), and try to add 2 reaction, i you succeed this, one of reaction will not be removed

![image](https://user-images.githubusercontent.com/46402441/120101925-e644b280-c148-11eb-9da2-51fcc07e4e22.png)

# Code Examples

```kt
class TestPaginator : Extension() {

    override val name: String
        get() = "test"

    override suspend fun setup() {
        command {
            name = "test"
            action {
                val pages = Pages()
                pages.addPage(Page(description = "a"))
                pages.addPage(Page(description = "b"))
                pages.addPage(Page(description = "c"))
                pages.addPage(Page(description = "d"))
                pages.addPage(Page(description = "e"))
                val paginator = Paginator(
                    pages = pages,
                    targetChannel = message.channel
                )
                paginator.send()
            }
        }
    }
}
```

# Suggestions

This is the code using to manage reaction :
```kt
while (true) {
                val condition = if (message.getChannelOrNull() is DmChannel) {
                    dmCondition
                } else {
                    guildCondition
                }

                val event = if (timeout != null) {
                    kord.waitFor(timeout = timeout, condition = condition)
                } else {
                    kord.waitFor(condition = condition)
                } ?: break

                processEvent(event)
}
```
The cause of this issue, is that between `processEvent` and the next `kord.waitFor`, no listening is done. So if in the processEvent, there is a `delay(10000)`, no other interaction is listened to while 10000ms

This is the same when page change for example, between the change (select, display page, and execute kord.waitFor), no interaction is listened to

A possibility is to use LiveEntity from Kord to always listen event and execute them in a queue (the queue is natural if only one job is used for all reactions)

**Comment by gdude2002** [comment]
**Note to self:** Fixing this is going to require custom event dispatcher logic. It's doable, it'll just take a while.

**Comment by gdude2002** [comment]
It's worth noting that Components will possibly obsolete this issue - the paginator will be able to move to real buttons at that point. We'll see, though.

**Comment by gdude2002** [comment]
The new paginators provide a much better UX and don't seem to have this particular problem, so I consider this issue resolved for now - the old paginator is marked as deprecated and will be removed in a future version.
