### ISSUE TITLE
Argument: Translate argument with specific bundle

### ISSUE THREAD

**Issue by Distractic** [Kotlin-Discord/kord-extensions#46]
# Summary

Add the possibility to use a specific `bundle` (for translation) in the command for his argument (description ..)

# Current Behaviour

When we use a translation key, the TranslationProvided do not find the key, because he search into the default bundle (Kordex)
For example, for a specific argument 
```kt
classMyCommand : Extension() {
  inner class MyArgs : Arguments() {
          val text by coalescedString(
              displayName = "mycommand.args.text.displayName", // The value is not translated with own bundle
              description = "mycommand.argstext.description" // The value is not translated with own bundle
          )
  }
  
  override suspend fun setup() {
        command(::Args) {
            name = "mycommand.name" // The value is not translated with own bundle
            description = "mycommand.description" // The value is not translated with own bundle
            ...
       }
   }
}
```

All key are translated with the default bundle (kordex bundle) and not the personal bundle

# Preferred Behaviour

Possibility to defined the bundle to translate the properties of a command and arguments

**Comment by gdude2002** [comment]
I'll work on this soon, but I'm going to move the functions for each converter into the file the converter is defined in, for the sake of making it easy to push things around.

**Comment by gdude2002** [comment]
This ticket isn't specific enough - from what I can find, the description should be translated properly. You haven't explained where incorrectly-translated strings are shown.

**Comment by Distractic** [comment]
There is already the property `bundle` for an Extension class. With that, this is possible to define with which bundle should be translated each keys into a command
