### ISSUE TITLE
Enum value aliases

### ISSUE THREAD

**Issue by bosukas** [Kotlin-Discord/kord-extensions#50]
# Summary

Provide a way of having aliases for enum values for arguments.

# Preferred Behaviour

Each enum value could have an array of aliases that we can provide, similar to how aliases for message commands work.
Maybe something like this:
```kt
enum class CoinSide(override val readableName: String, override val aliases: Array<String> = arrayOf()): ChoiceEnum {
	HEADS("heads", arrayOf("h")),
	TAILS("tails", arrayOf("t"))
}
```

**Comment by gdude2002** [comment]
Given the KordEx translations systems - and that Discord is largely moving to application commands, where aliases don't make sense - is this still needed?

**Comment by bosukas** [comment]
no
