### ISSUE TITLE
Argument parser overhaul

### ISSUE THREAD

**Issue by gdude2002** [Kotlin-Discord/kord-extensions#52]
The command argument parser needs an overhaul pretty badly:

* Converters are annoying to maintain, with many individual functions for applying them
* The argument parser always assumes that quoted arguments should have quotes stripped from them
* The argument parser has a ton of branching for each converter type

Here are my thoughts right now:

* We should use kotlinpoet to generate the converter functions instead of having to maintain them manually - although some of them will probably be impossible to generate, most of them should be pretty simple
* We should look into tokenization as a new approach to parsing, which would also allow us to yeet the Apache library - right now, I'm thinking two parsing parses would be required, with the first one parsing out keyword-style arguments before tokenizing the rest of the string, and iterating the converters. This would allow converters to decide precisely what they want the parser to do, if that's the route we'd like to go.
* It may be possible to unify converter interfaces by adding multiple typevars to the base `Converter` class, but I'm very wary of creating extra code spaghetti here

This is a very long ticket, and I'll need to update it later on. For now: input?

**Comment by gdude2002** [comment]
The first part of this issue is done - _most_ converters now have their converter functions generated via a KSP annotation processor.

More info on that is [in the docs](https://kordex.kotlindiscord.com/dev/concepts/converters/#generated-converter-functions).

**Comment by bosukas** [comment]
There is no way for converters to succeed without consuming any tokens. 

In the case of an Attachment Converter, where we take attachments as arguments, there's no current way of implementing this as if an attachment is provided, the argument consumes 0 tokens which we can't currently represent. Single Converters take 1 argument or fail, and Coalescing Converters will fail when you return 0 tokens consumed.

The new parsing system should allow converters to succeed without consuming any tokens.

**Comment by gdude2002** [comment]
This issue is mostly done - including @qbosst's comment. The only thing I wasn't able to do was to simplify the argument parser class itself, as it really _does_ have to branch for each converter type.

Converter base classes implement the `Converter` base, which takes four generics - input, output, named-input and result respectively.

```
CONVERTER                   GENERICS                                        OUTPUT
====================        =======================================         ==================
Coalescing                  List<T>, T,       List<String>, Int             T
Defaulting                  T,       T,       String,       Boolean         T = defaultValue
DefaultingCoalescing        List<T>, T,       List<String>, Int             T = defaultValue
Multi                       List<T>, List<T>, List<String>, Int             List<T> = listOf()
Optional                    T,       T?,      String,       Boolean         T? = null
OptionalCoalescing          List<T>, T?,      List<String>, Int             T? = null
Single                      T,       T,       String,       Boolean         T
```

As you can see, it's impossible to unify these types - they have differences that matter.

Otherwise, though, I'm quite happy with the changes. It'd be great to get some feedback, so I'm going to leave this issue open for a bit - just in case.

**Comment by gdude2002** [comment]
People seem largely happy with this, so I'm gonna consider it done for now.
