### ISSUE TITLE
Sentry feedback commands not registering

### ISSUE THREAD

**Issue by bosukas** [Kotlin-Discord/kord-extensions#54]
# Description

The sentry feedback commands are not getting registered, even though sentry itself is registered.
When looking through the help menu, there is nothing to indicate that there are feedback commands either.

# Versions

Kotlin 1.5, Kord-ex 1.4.1-Snapshot

# Reproduction

I am registering sentry in this order:
```kt
val bot = ExtensibleBot {
    // code
}

bot.getKoin().get<SentryAdapter>().init {
    // code
}

bot.start()
```

I have then made a simple command that throws an exception

```kt
command {
	name = "test"

	action {
		throw Exception("Just a test")
	}
}
```

This is the result I get
![image](https://user-images.githubusercontent.com/60557521/121426282-51715e80-c96b-11eb-922a-dc394c9aa73d.png)

**Comment by bosukas** [comment]
When trying to register the sentry (same code as above) in the `afterKoinSetup` hook, I get this error
```kt
21:50:05.618 [main] ERROR com.kotlindiscord.kord.extensions.builders.ExtensibleBotBuilder - Failed to run beforeKoinSetup hook () -> kotlin.Unit
org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.kotlindiscord.kord.extensions.sentry.SentryAdapter'. Check your definitions!
```

**Comment by gdude2002** [comment]
I pushed a commit that should correct that latter error - can you try it again with the new change?

**Comment by bosukas** [comment]
Yeah, it's registering the feedback commands now, thanks.

Just a note: the docs for this seem to be out of date, so you might wanna have a look at those

**Comment by gdude2002** [comment]
I think it may be better to give it the help extension treatment - a `sentry { }` block with a disabled-by-default Sentry extension, and initialisation stuff in that block which will also enable the extension with it. I'll look into that.

**Comment by bosukas** [comment]
Good idea.
While your at it, could you add an option to disable pings in replies for the message command variant, just like how you did with the help command?

**Comment by gdude2002** [comment]
This will be included in the next push.
