### ISSUE TITLE
Make automatic acknowledge type naming more consistent

### ISSUE THREAD

**Issue by imkunet** [Kotlin-Discord/kord-extensions#62]
# Summary

The naming for determining the mode of automatic interaction acknowledgement is inconsistent.

# Current Behavior

Right now in the component builder the field that determines the mode of automatic interaction acknowledgement is called "ackType" whereas the slash command's automatic acknowledgement field is called "autoAckType".

[Slash Commands Field](https://github.com/Kord-Extensions/kord-extensions/blob/develop/kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/commands/slash/SlashCommand.kt#L121)
[Components Field](https://github.com/Kord-Extensions/kord-extensions/blob/develop/kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/components/builders/ActionableComponentBuilder.kt#L47)

# Preferred Behavior

The preferred behavior is where the field names are consistent across the two different fields

# Suggestions

Personally I would like to see it be called "autoAckType" because the field name is easier for beginners using autocomplete (like myself) to understand exactly what this field controls quickly.

**Comment by gdude2002** [comment]
This is fixed in the latest snapshot - the property name was actually `autoAck`, not `autoAckType` or `ackType`.

I've deprecated the old name at the ERROR level, so that should help you with renaming.
