### ISSUE TITLE
Components setup function creates unnecessary listener when components only contains disabled buttons

### ISSUE THREAD

**Issue by bosukas** [Kotlin-Discord/kord-extensions#63]
# Summary

Disabled buttons are not actionable/clickable. When you send a message that only contains disabled buttons, the components setup function creates an unnecessary listener. 

![image](https://user-images.githubusercontent.com/60557521/126305765-0bdb29d5-4f4f-4b29-9a1f-e7e5bcfb252c.png)

# Preferred Behaviour

We should have a way of deciding whether we want to be able to listen for button events.

# Suggestions
I've come up with two possible solutions to this problem. We could either;

* have a parameter in the setup function that decides whether we want to listen for button events
* when the setup function is called, we iterate through every button and check if any of them are actionable buttons. If so, we enable the listener.

**Comment by gdude2002** [comment]
I'm still thinking about this util, honestly. It works for sure, but I'm starting to wonder if it's a great approach. Can you think of a better way? Perhaps delegating event handling to a central class to cut down on handler spam?

**Comment by bosukas** [comment]
Maybe we can have a central component registry similar to the `MessageCommandRegistry` and `SlashCommandRegistry`. The component registry would listen to interaction create events and check it against a map of interaction ids that we are currently listening to.

**Comment by gdude2002** [comment]
That's essentially what I had in mind, yeah - shouldn't be too complex to do.

**Comment by bosukas** [comment]
Yeah it would probably be easier to create util functions for disabling buttons as well with this new approach

**Comment by gdude2002** [comment]
This has been solved with the latest snapshot commit.
