### ISSUE TITLE
Add the addition emoji helpers from ButtonBuilder to SelectOptionBuilder

### ISSUE THREAD

**Issue by PotatoPresident** [Kotlin-Discord/kord-extensions#66]
# Summary

Add the addition emoji helpers from `ButtonBuilder` to `SelectOptionBuilder`.

# Current Behaviour

`SelectOptionBuilder` only accepts `PartialDiscordEmoji`

# Preferred Behaviour

Allow multiple emoji classes like `ButtonBuilder` does

**Comment by gdude2002** [comment]
Done. Current snapshots, next release.
