### ISSUE TITLE
Allow selecting a custom HTTP engine for Kord (niche request!)

### ISSUE THREAD

**Issue by pluiedev** [Kotlin-Discord/kord-extensions#69]
# Summary
Currently I have a (very) niche problem whenever I want to test or run my bot -- turns out that Kord defaults to use CIO for its default HTTP engine for Ktor, which has some bizarre issues with my proxy service that made the outward packets not handled by the proxy service. After some research I found out that my proxy is running under SOCKS, while CIO and Apache engines only support HTTP proxies for some godforsaken reasons.

After some more research I found out that Ktor also supports the [Java HTTP Client](https://openjdk.java.net/groups/net/httpclient/intro.html), which fully supports SOCKS proxies and after using some (concerning) hacks I was able to get it to work.

# Current Behaviour

The HTTP client is hardwired to use CIO, which is undesirable for my needs as mentioned above.

# Preferred Behaviour

Allow a field to be exposed in `ExtensionBotBuilder`, either of type `HttpClient` or `HttpClientEngineFactory<*>` to set customize the HTTP client or its engine. The latter may require modifying Ktor, but from what I can see, modifying `HttpClient` is perfectly acceptable within Ktor's APIs, as a `KordBuilder` can be specified to take a custom client, while all of the normal settings required to make it work still applies. 

# Suggestions

I noticed that only a selection of settings are customizable in `ExtensionBotBuilder`, presumably due to encapsulation concerns. But in addition to the ability to customize HTTP clients (which is arguably niche), I don't see why the `KordBuilder` cannot be customized with a configure function (like `KordBuilder.() -> Unit`). That would solve the entire problem, and may even prevent future problems like this showing up. 

# Media

<details>
    <summary>Current workaround</summary>
    <a href="https://gist.github.com/LeoCTH/bb84fdced2754e40b6d89ce2b7139475">Current workaround for this issue; some parts are redacted and/or deleted</a>
</details>

**Comment by gdude2002** [comment]
If Kord provides something for this, then I suspect it should be pretty easy to expose that, right? Can't imagine this being difficult.

**Comment by HopeBaron** [comment]
Kord allows setting `httpClient` in `KordBuilder` as long as it could install `Websockets` and `JsonFeature`

**Comment by pluiedev** [comment]
> Kord allows setting `httpClient` in `KordBuilder` as long as it could install `Websockets` and `JsonFeature`

Yeah that's what I did with the workaround. If I can do that with Kordex without duplicating a lot of code that would be good
<details>
<summary>Side note</summary>
<strike>I just found out that this is the 69th issue! Nice.</strike>
</details>

**Comment by gdude2002** [comment]
Instead of providing a direct abstraction for this, I'm adding a `kord` DSL function to the `ExtensibleBotBuilder` class. This will allow you to directly run code against the `KordBuilder`, which I think is a more future-proof solution for allowing users to customize Kord's behaviour.

This will be available in the next snapshot, but I'm hoping to get a release out soon!

Also: Nice.
