### ISSUE TITLE
Allow disabling feedback command when using sentry extension

### ISSUE THREAD

**Issue by kimcore** [Kotlin-Discord/kord-extensions#71]
# Summary

Allow disabling feedback command when using sentry extension.

# Current Behaviour

Currently, we can't disable the feedback command if the sentry extension is enabled.

# Preferred Behaviour

Users should be able to choose whether to create a feedback command or not.

# Suggestions

Expose a field in `SentryExtensionBuilder`, and check for that field in `ExtensibleBot.addDefaultExtensions`.

**Comment by gdude2002** [comment]
Done - this'll be available as the `feedbackExtension` Boolean prop in the `sentry` builder once the snapshot builds.

Note that `feedbackExtension` will be ignored if the Sentry integration is disabled.
