### ISSUE TITLE
Application Commands String Attributes Validation

### ISSUE THREAD

**Issue by Blacklands** [Kotlin-Discord/kord-extensions#73]
_Application Commands_ have various limitations on their `string` attributes, as can be seen [here](https://discord.com/developers/docs/interactions/application-commands).
For example, the name of a command must have a length of 1-32 characters, its description must have one of 1-100 characters.
_Options_ names for the commands are even stricter, they must be all-lowercase as well.

Currently, Kord Extensions just takes plain strings for these attributes, and seems to do no checks on them "behind the scenes" either.
I only just discovered these limits, by accident, because Kord Extensions threw an exception when trying to register the commands:

```
[kord.extensions.commands.slash.SlashCommandRegistry]: Failed to sync slash commands for guild ID: Snowflake(value=[snip])
dev.kord.rest.request.KtorRequestException: REST request returned with HTTP 400 Bad Request. InvalidFormBody: Invalid Form Body
[...]
```

I had to dig through the contents of the JSON in the debug logs to find out what the actual problem was:

```
body:{"code": 50035, "errors": {"1": {"description": {"_errors": [{"code": "BASE_TYPE_BAD_LENGTH", "message": "Must be between 1 and 100 in length."}]}}}, "message": "Invalid Form Body"}
```

Is there any interest in adding some code to do these validations earlier (before even attempting to register the commands)?
That would allow at least for better error messages (could throw a fitting exception as soon as an invalid command attribute is encountered, with a description detailing the issue).

For example, the types of `name`, `description` and the like within the command builders could be changed to custom types that take `String`s in their constructors, do the validation there and throw an exception if needed.
That would make it clear in the type system that `name`, `description` and so on cannot be arbitrary strings, but have some limitations associated with them. Although this would be a breaking change, I suppose...

Alternatively, the contents could be checked when the actual `SlashCommand` instance is created from the DSL, and an exception be thrown at that point?

Or, maybe you don't want to do a forced validation in the code like that, since if the Discord API changes these limitations, the code might reject (now) valid data?
I don't know how volatile the Discord API is. I know that Application Commands in general are also a quite recent addition, and so are maybe subject to more rapid changes down the line - so this might end up being wasted development time, in the worst case...
Maybe the exception message when failing to register the Application Commands could simply be improved?

**Comment by gdude2002** [comment]
I'll add this to #72 when I get a chance, but the issue with checking these things early is that translation keys are almost never the same length as the resulting name. I think we can still reasonably validate them though, just need to figure out the correct time to do so.

**Comment by gdude2002** [comment]
Small update - I poked @HopeBaron about parsing the JSON out of the error response when Discord responds with one. He said he's looking into it - although it may be a while, it'd be nice to be able to just get the error from the exception instead of having to hardcode validation for it.

**Comment by HopeBaron** [comment]
This change has been added a while back https://github.com/kordlib/kord/commit/0f43fe4df7064a614e924c8156612346e1dcafd1

**Comment by gdude2002** [comment]
Hmm, so it was. I see that the JSON error codes have no human-readable version, though, which is unfortunate - usually I'd add something for it myself, but that's a looooot of stuff.

Though, it's an enum, so I can just stringify it, right?

**Comment by HopeBaron** [comment]
Are we referring to this: [JsonErrorCode.kt - 0.8.x](https://github.com/kordlib/kord/blob/0.8.x/rest/src/main/kotlin/json/JsonErrorCode.kt) ?

**Comment by gdude2002** [comment]
yes

**Comment by gdude2002** [comment]
While it was tempting to do specific hardcoded validation here, Discord's basic requirements for application commands are subject to change - so, I elected to use the error message Discord provides at registration time, rather than hardcoding early validation. This should make things easier to understand, but still allow for flexibility, meaning that Discord changing its requirements won't break KordEx.

This is in the latest push to the develop branch, so it should be available in the next snapshot build. I'll leave this issue open for a bit, to give you time to test the solution.

**Comment by gdude2002** [comment]
It's been about a week, so I'll assume this has been solved in a satisfactory way. o7
