### ISSUE TITLE
Command Events

### ISSUE THREAD

**Issue by bosukas** [Kotlin-Discord/kord-extensions#75]
# Summary

I would like to log stats about which commands are being used the most, which commands do people have trouble with the most, etc. Would you be able to add events that we can listen to for commands?

# Preferred Behaviour

These are examples for slash commands, but they should be added to all command types.

```kt
event<OnSlashCommandExecuted> {
    action {
        event.command
    }
}

event<OnSlashCommandFailure> {
    action {
        event.command
        event.exception
    }
}
```

**Comment by gdude2002** [comment]
Hmm, that's a pretty interesting idea. Currently this'd be done using replacements for the various registry classes, but I think this is a fair thing to support natively as well. Worth looking into once we hit a 1.5.x release!

**Comment by gdude2002** [comment]
This has been implemented and will be available in the next snapshot. See here for the classes - there's a _lot_ of typed events here: https://github.com/Kord-Extensions/kord-extensions/tree/develop/kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/commands/events

I have a suspicion that this changeset may cause a small performance hit. Let me know if you notice any slowdowns, please.

<blockquote><img src="https://opengraph.githubassets.com/248c779f42c0503fe8a3155ace3005675d285d605eefcc52845ae333cbfe3d89/Kord-Extensions/kord-extensions" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Kord-Extensions/kord-extensions">kord-extensions/kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/commands/events at develop · Kord-Extensions/kord-extensions</a></strong></div><div>Kord extensions framework, providing commands and distinct units of functionality - kord-extensions/kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/commands/events at develop · Ko...</div></blockquote>

**Comment by bosukas** [comment]
This looks pretty good, thank you!
For the failed parsing event, would it be possible to have access to the argument object?

**Comment by gdude2002** [comment]
Well, it failed to parse, so the converter would be empty. I guess it should still be possible, though.

**Comment by gdude2002** [comment]
Latest push should make this possible now.

**Comment by gdude2002** [comment]
Working okay for you, @qbosst?

**Comment by bosukas** [comment]
Looks all good, you can close this issue

**Comment by gdude2002** [comment]
Gotcha, thanks for the suggestion!
