### ISSUE TITLE
waitFor user message

### ISSUE THREAD

**Issue by kentogruener** [Kotlin-Discord/kord-extensions#79]
# Suggestions

Specific API to await messages from users

**Comment by gdude2002** [comment]
The latest push contains the following functions:

* A general `waitForMessage`
* `MessageChannelBehavior.waitForMessage`
* `UserBehavior.waitForMessage`
* `MessageBehavior.waitForReply`
* `CommandContext.waitForResponse`

Hopefully that'll sort you out for now.

**Comment by bosukas** [comment]
Would it be possible to allow for the waitFor functions to take in the `Arguments` class and it would parse it like a command?

**Comment by gdude2002** [comment]
You're asking for a conversational API, which is something I started planning in #57

**Comment by gdude2002** [comment]
As this has been implemented and no feedback has been provided, I'll assume this issue is solved. Feel free to comment or open a new issue if there are further things to discuss.
