### ISSUE TITLE
Add a util method that calculates the intents an extension uses

### ISSUE THREAD

**Issue by bosukas** [Kotlin-Discord/kord-extensions#80]
# Summary

I use to be able to calculate the intents an extension uses by iterating through all the event handlers and running it through Kord's `getIntents(event`) method, however the event handler doesn't provide the KClass of the event type anymore.

# Preferred Behaviour

Add a util method that calculates the intents for an extension or allow us to do it by giving us the event or event class type in the `EventHandler`

**Comment by gdude2002** [comment]
I'm going to need your list of events to intents before I can start on this.

**Comment by bosukas** [comment]
I used Kord's `getIntents(event)` method, so the list of events to intents would be there

**Comment by gdude2002** [comment]
Alright, I've done one better - this entire feature (the automatic enabling of intents) has been added, and will be available once the next snapshot has built.

I've already updated the docs for the `intents` DSL in the `ExtensibleBotBuilder`, please take a look a that, try this out, and let me know what you think!

**Comment by bosukas** [comment]
This looks good, thank you!
I think the only thing I would want before closing the issue is for chat commands to also enable the direct messages intent

**Comment by gdude2002** [comment]
They currently enable guild messages - I'll check if there are other intents

**Comment by gdude2002** [comment]
I don't think `DirectMessages` is what you want.

```kotlin
    /**
     * Enables the following events:
     * - [ChannelCreate]
     * - [ChannelDelete]
     * - [MessageUpdate]
     * - [MessageDelete]
     */
    object DirectMessages : Intent(1 shl 12)
```

I gave it `GuildMessages` already:

```kotlin
    /**
     * Enables the following events:
     * - [MessageCreate]
     * - [MessageUpdate]
     * - [MessageDelete]
     * - [MessageDeleteBulk]
     */
    object GuildMessages : Intent(1 shl 9)
```

Surely that's what you want?

**Comment by bosukas** [comment]
I guess it just depends on whether you think enough people will be using chat commands to also respond to DMs

**Comment by gdude2002** [comment]
So you need `DirectMessages` for DMs? Alright then, I can still do that.

**Comment by gdude2002** [comment]
Aaand that's pushed.

**Comment by gdude2002** [comment]
It's been 20 days, so I'll assume that this is good.
