### ISSUE TITLE
Convenience util methods for env

### ISSUE THREAD

**Issue by bosukas** [Kotlin-Discord/kord-extensions#81]
# Summary

Currently the env method returns a null string if the variable is not present. I find that typically I add a null check and throw an error if the variable is missing for most envs. (`env("token") ?: error("token is missing")`).

I imagine most people probably have something similar too. Maybe we can make the env function throw an error by default if its missing, and add a `envOrNull` function?

I feel like this change would be small but be way more convenient

**Comment by gdude2002** [comment]
You know the drill!

**Comment by bosukas** [comment]
Appears as though it's working, thank you!

**Comment by gdude2002** [comment]
:+1:
