### ISSUE TITLE
Java 8 support?

### ISSUE THREAD

**Issue by slava110** [Kotlin-Discord/kord-extensions#82]
Hi. I wanted to use Kord Extensions in my project but it looks like it only supports Java 9 (while Kord supports Java 8). Is it possible to support Java 8? Or should I fork it to use in my project?

**Comment by gdude2002** [comment]
Hey, thanks for the issue.

At the moment, some KordEx modules make use of Java time APIs that only existed since Java 9. That said, I don't think the _core_ uses it - it should be possible to drop the API level a bit, and it should just work, but I can't check right at this moment.

I assume you're coming from the Minecraft community, looking at your repos?

**Comment by slava110** [comment]
Yeah, that's right. As I'm working on older Minecraft version I'm unable to use Java 9 in my project

**Comment by gdude2002** [comment]
Gotcha. I'm looking at this now, just running a test build.

**Comment by gdude2002** [comment]
Yes, this seems to build just fine. I'll get a push out for 1.5.0-SNAPSHOT shortly.

**Comment by gdude2002** [comment]
I believe that should be about published - let me know how you get on!

**Comment by slava110** [comment]
Yeah, it works! Thanks!
As about time API you're using... If you mean [this stuff](https://github.com/Kord-Extensions/kord-extensions/blob/root/modules/java-time/src/main/kotlin/com/kotlindiscord/kord/extensions/modules/time/java/ChronoContainer.kt#L190) you can replace it with `duration.seconds % SECONDS_PER_MINUTE`, `duration.toMinutes() % MINUTES_PER_HOUR`, etc. (you have these variables [here](https://github.com/Kord-Extensions/kord-extensions/blob/root/modules/java-time/src/main/kotlin/com/kotlindiscord/kord/extensions/modules/time/java/ChronoContainer.kt#L32) anyway). It will do the same thing without converting it to `Int`

**Comment by gdude2002** [comment]
In our case, using java time types is kind of the point - it's for the java time API module. Either way, glad things are working now!
