### ISSUE TITLE
Flexible state handling for slash commands and components

### ISSUE THREAD

**Issue by ByteAlex** [Kotlin-Discord/kord-extensions#86]
# Summary

In the current implementation of KordEx, the entire state of slash commands and components is only accessible in the virtual environment. Distributed setups with multiple bot instances are facing an issue there, commands/components which are registered/created on one VM can not properly be accessed/used on other VMs.
This is a major and blocking issue for my use case.

# Current Behaviour
The state "internal ids" are stored in a local hashmap, which is not VM agnostic and losing all information with shutdown of the VM.

# Suggestions / Preferred Behaviour
I can imagine two ways of handling this:
a) Give commands & components an own discord-agnostic id, which is constant across VMs and throughout restarts. This would eventually make it possible to use KordEx in distributed environments.
b) Install an interface to store state, which can default to a "local" (HashMap or similar) implementation, but it pluggable to switch to a networke'd state-store like redis for example (to stay with simple key-value bindings). Though I also can imagine a SQL table for slash commands, since those should be more persistant.

Possibly a mix of both would result in the best dev-experience and have a solid feature set for distributed bots.

**Comment by gdude2002** [comment]
It's certainly an interesting idea.

> Give commands & components an own discord-agnostic id, which is constant across VMs and throughout restarts. This would eventually make it possible to use KordEx in distributed environments.

Technically speaking, this is already done. Components have unique IDs _by default_ (they're given a stringified UUID), and commands must have unique names in their own scopes (guild/global and message/slash/user) - which effectively is an ID of sorts. The Snowflake to command mapping only exist because Discord keys them by Snowflake. 

I'm not sure what you specifically want from such a system, given the above.

> Install an interface to store state, which can default to a "local" (HashMap or similar) implementation, but it pluggable to switch to a networke'd state-store like redis for example (to stay with simple key-value bindings). Though I also can imagine a SQL table for slash commands, since those should be more persistant.

I see no problem with doing this, but I get the feeling that the current access methods might not suit your use-case. Can you be more specific with what you need?

---

My assumption from your questions on Discord was that what you actually wanted was a way to register reusable command/component actions/builders to IDs, which would mean you'd have your own registry of actions/builders, and you'd just tell the commands DSL which IDs to use. That seems like a more logical approach to me.

**Comment by ByteAlex** [comment]
Thank you very much for your quick answer!

> Technically speaking, this is already done. Components have unique IDs by default (they're given a stringified UUID), and commands must have unique names in their own scopes (guild/global and message/slash/user) - which effectively is an ID of sorts. The Snowflake to command mapping only exist because Discord keys them by Snowflake.

That's great, meaning the second part could be easily implemented I presume.

> I see no problem with doing this, but I get the feeling that the current access methods might not suit your use-case. Can you be more specific with what you need?

I'll gladly explain more what or why I need that.
In my distributed environment, every component should hold no local state.
There could be 3 "kord instances" running, and each of them is getting events for the same shard, but that event is at most delivered once.
Moving forward, if - I call it Kord 1 - is creating application commands or components and the next InteractionCreate is handled on Kord 2, none of them would work, because the state for those is only contained in Kord 1. 
The second issue, which is heavily related ot the above one is simply that the local state is lost through restarts.

Having a shared state in redis or any other persistence would resolve both of those issues, I assume.
This is why I was asking for an interface to store the state.

I hope this explains my use case! 👍 

> My assumption from your questions on Discord was that what you actually wanted was a way to register reusable command/component actions/builders to IDs, which would mean you'd have your own registry of actions/builders, and you'd just tell the commands DSL which IDs to use. That seems like a more logical approach to me.

I think this ties in with the interface, as we talked about in DMs; You cannot serialize a callback and thus this is probably part of the interface change I suggested. Each component/application needs to be linked to its correct DSL.

**Comment by gdude2002** [comment]
I think an early first approach that just swaps out the storage implementation is the way to go to begin with, and then we can look into registry-capable callables after, potentially in a module since it's such a specific thing. We can see how things shape up after the storage is done, at any rate.

**Comment by ByteAlex** [comment]
The callback registry and the following change with "checks and actions" already helped alot, but we still have to construct a "dummy" button, since we have no idea about the button data.
Since the interaction event passes along all message data, we can iterate through the components and find the matching button by it's custom-id and pass that data to the "reconstructing" interface.

**Comment by gdude2002** [comment]
It's not clear from the remaining context in this issue whether there's more work to be done. Can you remind me on that?

**Comment by ByteAlex** [comment]
I think reconstructing the entire button data from the message data was the last thing, which was open.
I.e. we do know the button-id (custom_id) and we get the message.components, so we can reconstruct the entire button data from that.

**Comment by gdude2002** [comment]
At what point in execution was that meant to happen, again?

**Comment by ByteAlex** [comment]
Sorry, forgot to answer here; It was supposed to happen once we receive an InteractionCreateEvent, since in that context we eventually do not know the button object.

**Comment by gdude2002** [comment]
It's been a while since we've talked about this - what state is this ticket in regarding modern KordEx?

**Comment by gdude2002** [comment]
Given that this issue has been abandoned since October of last year (despite being marked high priority) and I know that @ByteAlex has moved on to a custom framework written by @WinteryFox, I'm closing this issue now. If anyone would like to see further work on this subject, please open another issue!
