### ISSUE TITLE
Kordex puts all application commands into lower case

### ISSUE THREAD

**Issue by DRSchlaubi** [Kotlin-Discord/kord-extensions#87]
All application commands automatically put the names into lower case .

However the context commands also allow upper case names, so that limit should be removed there

**Comment by gdude2002** [comment]
The latest push should handle this. It also uses case-insensitive matching for command names when syncing with Discord, but that shouldn't be an issue for you.

Let me know how this goes for you!

**Comment by gdude2002** [comment]
Closing due to lack of response. If this isn't solved, well, your loss!
