### ISSUE TITLE
Hooks builder for extensions

### ISSUE THREAD

**Issue by bosukas** [Kotlin-Discord/kord-extensions#89]
# Summary

I want to configure some private variables in my extension based on hooks, (e.g. afterExtensionsAdded, extensionAdded), I was wondering if you could add a hooks builder to extensions, similar to the one in the extensible bot builder?

**Comment by gdude2002** [comment]
This seems like it'd be much better suited for the events system - for example, the extension state change event. Is there a reason that doesn't help you?

**Comment by bosukas** [comment]
I need an event that runs after all the extensions have been added, is there an event like that already?

**Comment by gdude2002** [comment]
Not at the moment, but what are you trying to do there?

**Comment by bosukas** [comment]
I have an invite command and for the invite link you need the bot permissions. So I have a private permissions variable that gets calculated after all the extensions have been added by iterating through every command and applying its `requireBotPermissions` method to a permission builder

**Comment by gdude2002** [comment]
Oh, I see, permissions inheritance.

That really seems like something that should be done in an Extension subclass, though - what specifically does the iterating _after_ load get you?

**Comment by bosukas** [comment]
Not sure what you mean `after load`
I have a method to calculate the permissions in an extension subclass and I call the method in the `afterExtensionsAdded` hooks builder

**Comment by gdude2002** [comment]
Right, but why are you doing that then instead of doing it in `doSetup`?

**Comment by bosukas** [comment]
Are all the commands and extensions loaded in the `onSetup` ? 
Theres no difference to me where it goes, just as long as the extension is setup

**Comment by gdude2002** [comment]
No, I mean, `doSetup` in the extension itself

**Comment by bosukas** [comment]
I could, but that would only get me the permissions for the extension that's being setup

**Comment by gdude2002** [comment]
Yes but you haven't said why that won't help

**Comment by bosukas** [comment]
i need the permissions for all the commands my bot has so that I can generate the invite link for it

**Comment by gdude2002** [comment]
Oh I see, you didn't mean a server invite link, you meant the OAuth link. Okay.

So why do you need to generate the invite link from another extension in that case?

**Comment by bosukas** [comment]
Yeah an oauth link, I generate it in an extension because there's a command to display the invite like for it so it makes sense to calculate the permissions there

**Comment by gdude2002** [comment]
Well why do you need a hook then? You could just calculate it at command
run time and cache the result, no? Or maybe calculate it at the ready
event?

**Comment by bosukas** [comment]
I guess I could do that, for some reason my mind didn't think of that

**Comment by gdude2002** [comment]
:+1:
