### ISSUE TITLE
Interaction Converters rely on cache instead of "resolved"

### ISSUE THREAD

**Issue by ByteAlex** [Kotlin-Discord/kord-extensions#93]
# Description

InteractionCreate events provide an easy access to all data mentioned in the command via their "resolved" field.
This field is not being used by KordEx Converters, instead KordEx tries to fetch those entities from the cache.

# Expected Behaviour

KordEx should use the "resolved" field for data resolution.

**Comment by gdude2002** [comment]
This should be addressed in the commit I just pushed. Let me know how you get on with it!

**Comment by ByteAlex** [comment]
This works, great work, thank you!
